parameters:
    open_tracing.tracer.service_name: 'symfony-open-tracing'
    open_tracing.tracer.config:
          sampler:
              type: 'const'
              param: true
          local_agent:
              reporting_host: 0.0.0.0
          logging: true
          null_tracer: false
          max_buffer_length: 9000 # !important! should be less than output of command sysctl net.inet.udp.maxdgram
