services:
    open_tracing.tracer:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\Service\OpenTracingService
        arguments:
            - 'symfony-open-tracing'
            - sampler:
                type: 'const'
                param: true
              local_agent:
                reporting_host: 0.0.0.0
              logging: true

    open_tracing.http_listener:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\EventListener\HttpListener
        arguments:
          - '@open_tracing.tracer'
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.terminate }
            - { name: kernel.event_listener, event: kernel.exception }
