services:
    open_tracing.tracer:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\Service\OpenTracingService
        arguments:
            - '%open_tracing.tracer.service_name%'
            - '%open_tracing.tracer.config%'

    open_tracing.name_getter:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\Service\RootSpanNameBuilder
        arguments:
            - 'http-tracing'
            - 'cli-tracing'

    open_tracing.http_listener:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\EventListener\HttpListener
        arguments:
          - '@open_tracing.tracer'
          - '@open_tracing.name_getter'
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.terminate }
            - { name: kernel.event_listener, event: kernel.exception }
